-- 코이노니아 예약 데이터 (구글 시트 → Supabase 이전)
-- 설계: docs/superpowers/specs/2026-09-19-supabase-migration-design.md
-- 적용: Supabase 대시보드 > SQL Editor에 전체를 붙여넣고 Run. 한 번만 실행한다.

-- ── 예약 (살롱 + 스테이) ─────────────────────────────
create table public.bookings (
  id            bigint generated by default as identity primary key,
  sheet_row     integer,                -- 이전해 온 행의 원래 시트 행 번호. 새 행은 null
  kind          text not null check (kind in ('salon', 'stay')),
  created_at    timestamptz,            -- 수기 입력 행은 비어 있을 수 있다
  name          text not null default '',
  phone         text not null default '',
  phone_digits  text generated always as (regexp_replace(phone, '\D', '', 'g')) stored,
  program       text not null default '',
  date_text     text not null default '',
  room          text not null default '',
  nights        text not null default '',
  check_in      text not null default '',
  check_out     text not null default '',
  discount      text not null default '',
  total_amount  integer,
  memo          text not null default '',
  status        text not null default '신청',
  notify_status text not null default '',
  unique (kind, sheet_row)
);
create index bookings_kind_created_idx on public.bookings (kind, created_at desc);
create index bookings_phone_digits_idx on public.bookings (phone_digits);

-- ── 리트릿 ───────────────────────────────────────────
create table public.retreats (
  id           bigint generated by default as identity primary key,
  sheet_row    integer unique,
  created_at   timestamptz,
  name         text not null default '',
  phone        text not null default '',
  phone_digits text generated always as (regexp_replace(phone, '\D', '', 'g')) stored,
  grade        text not null default '',
  region       text not null default '',
  session      text not null default '',  -- 회차 라벨 문자열 (시트와 동일)
  referral     text not null default '',
  question     text not null default '',
  memo         text not null default '',
  allergy      text not null default '',
  care         text not null default '',
  parent_note  text not null default '',
  status       text not null default '신청'
);
create index retreats_phone_digits_idx on public.retreats (phone_digits);

-- ── 무료개방 ─────────────────────────────────────────
create table public.open_stays (
  id           bigint generated by default as identity primary key,
  sheet_row    integer unique,
  created_at   timestamptz,
  name         text not null default '',
  phone        text not null default '',
  phone_digits text generated always as (regexp_replace(phone, '\D', '', 'g')) stored,
  email        text not null default '',
  check_in     text not null default '',
  check_out    text not null default '',
  group_type   text not null default '',
  group_size   text not null default '',
  reason       text not null default '',
  contribution text not null default '',
  message      text not null default '',
  status       text not null default '신청'
);
create index open_stays_phone_digits_idx on public.open_stays (phone_digits);

-- ── 일괄 처리 기록 ───────────────────────────────────
-- job_id는 unique가 아니다: 되돌린 뒤 같은 대상을 다시 실행하면 같은 jobId가 또 생긴다(조회는 최신 것).
create table public.bulk_logs (
  id          bigint generated by default as identity primary key,
  sheet_row   integer unique,
  job_id      text not null,
  at          text not null,             -- KST "YYYY-MM-DD HH:mm:ss"
  filter      jsonb not null,
  action      text not null,
  notify      boolean not null,
  count       integer not null,
  snapshot    jsonb not null,            -- [{ ref: {tab, id}, status, notify }]
  reverted_at text not null default ''
);
create index bulk_logs_job_id_idx on public.bulk_logs (job_id, id desc);

-- ── 보안: RLS 켜고 정책 없음 = anon/authenticated는 전부 거부. 서버만 service role로 접근 ──
alter table public.bookings   enable row level security;
alter table public.retreats   enable row level security;
alter table public.open_stays enable row level security;
alter table public.bulk_logs  enable row level security;
revoke all on table public.bookings, public.retreats, public.open_stays, public.bulk_logs
  from anon, authenticated;
-- Supabase는 기본 권한 부여를 없애는 중이다. 명시하지 않으면 service_role 호출도 42501로 거부되고
-- reset_id_sequences()의 setval도 실패한다.
grant select, insert, update, delete on table public.bookings, public.retreats, public.open_stays, public.bulk_logs
  to service_role;
grant usage, select, update on all sequences in schema public to service_role;

-- ── 일괄 처리: 한 트랜잭션으로 전부 반영하거나 하나도 반영하지 않는다 ──
-- patches: [{ "id": 12, "status": "입금확인", "notify": "🔕 14:32 확정 알림 없음" }, ...]
-- 키가 없는 필드는 그대로 둔다. 빈 문자열은 빈 문자열로 쓴다(되돌리기에 필요).
create or replace function public.apply_booking_patches(patches jsonb)
returns integer
language plpgsql
security invoker
set search_path = public
as $$
declare
  p jsonb;
  hit integer;
  total integer := 0;
begin
  for p in select * from jsonb_array_elements(patches) loop
    update public.bookings
       set status        = coalesce(p->>'status', status),
           notify_status = coalesce(p->>'notify', notify_status)
     where id = (p->>'id')::bigint;
    get diagnostics hit = row_count;
    if hit = 0 then
      raise exception 'booking id % not found', p->>'id';
    end if;
    total := total + hit;
  end loop;
  return total;
end;
$$;
revoke execute on function public.apply_booking_patches(jsonb) from public, anon, authenticated;
grant execute on function public.apply_booking_patches(jsonb) to service_role;

-- ── 백업 복구 후 id 시퀀스를 max(id)+1로 맞춘다 ──
create or replace function public.reset_id_sequences()
returns void
language plpgsql
security invoker
set search_path = public
as $$
declare
  t text;
begin
  foreach t in array array['bookings', 'retreats', 'open_stays', 'bulk_logs'] loop
    execute format(
      'select setval(pg_get_serial_sequence(%L, ''id''), coalesce((select max(id) from public.%I), 0) + 1, false)',
      'public.' || t, t
    );
  end loop;
end;
$$;
revoke execute on function public.reset_id_sequences() from public, anon, authenticated;
grant execute on function public.reset_id_sequences() to service_role;
